<a href="https://colab.research.google.com/github/07shi/PYTHON/blob/main/Numpy%20Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Sum and Mean
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# Max and Min
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

# Reshape
reshaped = arr.reshape(2, 3)
print("Reshaped Array:\n", reshaped)

# Element-wise Multiplication
result = arr * 2
print("Element-wise Multiplication:\n", result)

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Element-wise Multiplication:
 [ 2  4  6  8 10 12]
